import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import AuthProvider from '@/components/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CRUD',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-gradient-to-br from-slate-50 to-slate-200 text-slate-800`}>
          <AuthProvider>
            <div className='max-w-3xl mx-auto p-4'>
              <Navbar />
              <div className='mt-8'>{children}</div>
            </div>
          </AuthProvider>
          <Toaster position="top-right" />
      </body>
    </html>
  )
}
